name: Deploy images to GHCR

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      actions: read
      checks: read
      deployments: read
      pull-requests: read
      repository-projects: read
      statuses: read

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the docker image
        run: |
          docker build -t leo.dotslashsteve.sh .

      - name: Tag the Docker images
        run: |
          docker tag leo.dotslashsteve.sh ${{ env.REGISTRY }}/${{ github.actor }}/leo.dotslashsteve.sh:latest

      - name: Push Docker Images to GHCR
        run: |
          docker push ${{ env.REGISTRY}}/${{ github.actor }}/leo.dotslashsteve.sh:latest
